# Generated by Django 5.0.6 on 2024-05-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Menu name')),
                ('description', models.TextField(verbose_name='Menu description')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=255, verbose_name='Menu dish')),
                ('content', models.TextField(blank=True, verbose_name='Description')),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.menu', verbose_name='Choose menu')),
            ],
            options={
                'verbose_name': 'Dishes',
                'verbose_name_plural': 'Dish',
            },
        ),
    ]
